"""Added author to Org table

Revision ID: 869e735eecd3
Revises: ded81bea700c
Create Date: 2023-09-04 13:26:13.460235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869e735eecd3'
down_revision = 'ded81bea700c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('organization_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('organization_author_id_fkey', 'user', ['author_id'], ['id'])
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
